version: "3"
services:
  app:
    build: ./php
    volumes:
      - ..:/workspace:cached  # for VSCode workspace
      - ../src/:/var/www/html # deploy to web root

  web:
    image: nginx:1.17-alpine
    depends_on:
      - app
    ports: 
      - "8080:80"
    volumes:
      - ../logs:/var/log/nginx
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
