version: "3"
services:
  app:
    build: ./php
    depends_on:
      - db
    volumes:
      - ..:/workspace:cached      # for VSCode workspace
      - ../backend:/var/www/html  # deploy to web root

  web:
    image: nginx:1.17-alpine
    depends_on:
      - app
    ports: 
      - "8080:80"
    volumes:
      - ../backend:/var/www/html  # deploy to web root
      - ../logs:/var/log/nginx
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  db:
    image: postgres:12.2
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'ZtG*GSdvdT_W'
      POSTGRES_DB: 'laravel_db'
